//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ajustesGenerales : global::System.Configuration.ApplicationSettingsBase {
        
        private static ajustesGenerales defaultInstance = ((ajustesGenerales)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ajustesGenerales())));
        
        public static ajustesGenerales Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Valor {
            get {
                return ((string)(this["Valor"]));
            }
            set {
                this["Valor"] = value;
            }
        }
    }
}
